# Generated by Django 3.0.6 on 2020-06-06 22:48

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_post', models.CharField(max_length=100)),
                ('description_of_post', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('application_deadline', models.DateField(default=django.utils.timezone.now, verbose_name='Application Deadline')),
                ('skills_needed', models.TextField(blank=True)),
                ('num_of_positions', models.IntegerField()),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None)),
                ('post_made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bookmarked_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts_app.PostModel')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedPostsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('applied_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts_app.PostModel')),
            ],
        ),
    ]
