# Generated by Django 3.0.6 on 2020-06-06 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='application_deadline',
        ),
    ]
