# Generated by Django 3.0.6 on 2020-06-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0004_postmodel_applicants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='applicants',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='application_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='current_num_of_accepted_applicants',
            field=models.IntegerField(default=0),
        ),
    ]
