# Generated by Django 3.0.6 on 2020-06-09 22:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0005_auto_20200609_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='applicants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
