# Generated by Django 3.0.6 on 2020-06-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0007_postmodel_accepted_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedpostsmodel',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
