# Generated by Django 3.0.6 on 2020-06-12 19:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0008_appliedpostsmodel_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='accepted_applicants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='applicants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
