# Generated by Django 3.0.6 on 2020-06-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0009_auto_20200612_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkedmodel',
            name='deadline_notification',
            field=models.BooleanField(default=False),
        ),
    ]
