# Generated by Django 3.0.6 on 2020-06-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0010_bookmarkedmodel_deadline_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarkedmodel',
            name='deadline_notification',
        ),
        migrations.AddField(
            model_name='bookmarkedmodel',
            name='days_left',
            field=models.IntegerField(default=3),
        ),
    ]
