# Generated by Django 3.0.6 on 2020-06-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='post',
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='title',
            field=models.CharField(default='Title', max_length=50),
        ),
    ]
