# Generated by Django 3.0.6 on 2020-06-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200615_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='key',
            field=models.IntegerField(default=0),
        ),
    ]
