# Generated by Django 3.0.6 on 2020-06-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmodel_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='key',
            field=models.BigIntegerField(default=0),
        ),
    ]
