# Generated by Django 3.0.6 on 2020-06-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200617_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='owner',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='url',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
