# Generated by Django 3.0.6 on 2020-06-21 19:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20200620_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='chat_name',
            field=models.CharField(blank=True, default='Chat', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
        ),
    ]
