# Generated by Django 3.0.6 on 2020-07-07 21:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20200621_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 21, 17, 33, 220306, tzinfo=utc), verbose_name='date_updated'),
        ),
    ]
