# Generated by Django 3.0.6 on 2020-07-07 21:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chatmodel_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 21, 47, 16, 631861, tzinfo=utc), verbose_name='date_updated'),
        ),
    ]
