# Generated by Django 3.0.6 on 2020-06-17 21:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize_main', '0003_account_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='chat_keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
