# Generated by Django 3.0.6 on 2020-06-17 22:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize_main', '0004_account_chat_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='chat_keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, size=None),
        ),
    ]
