# Generated by Django 3.0.6 on 2020-06-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize_main', '0005_auto_20200617_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(default='media/default_profile.png', upload_to='media'),
        ),
    ]
