# Generated by Django 3.0.6 on 2020-06-23 23:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize_main', '0010_auto_20200623_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='friends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
