# Generated by Django 3.0.6 on 2020-06-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='notified_message',
            field=models.TextField(),
        ),
    ]
